#headless service
apiVersion: v1
kind: Service
metadata:
  name: mongodb-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: mongodb
    tier: db
  ports:
  - protocol: TCP
    port: 27017 # service port
    targetPort: 27017 # container port