#headless service
apiVersion: v1
kind: Service
metadata:
  name: redis-headless
  namespace: roboshop
spec:
  clusterIP: None
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
  - protocol: TCP
    port: 6379 # service port
    targetPort: 6379 # container port
